name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Continue with your CMake steps
      - name: Configure the project with CMake
        run: |
          mkdir -p build
          cmake -S . -B build -DBUILD_TESTS=ON

      # Build the project
      - name: Build the project
        run: |
          cmake --build build

      # Run the tests
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      # Final message
      - name: Build and test process completed
        run: echo "Build and test process completed successfully!"
