name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Google Test (GTest)
      - name: Install Google Test
        run: |
          sudo apt-get install -y libgtest-dev
          sudo apt-get install -y cmake # GTest requires cmake

          # Build and install Google Test manually
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib

      # Clean the build directory to remove previous CMake cache
      - name: Clean the build directory
        run: |
          rm -rf build
          mkdir build
      
      # Continue with your CMake steps
      - name: Configure the project with CMake
        run: |
          cmake -S . -B build -DBUILD_TESTS=ON

      # Build the project
      - name: Build the project
        run: |
          cmake --build build

      # Run the tests
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      # Final message
      - name: Build and test process completed
        run: echo "Build and test process completed successfully!"
