name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies (including CMake, GCC, and GTest)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev
          
          # Install GCC 13 for C++23 support (C++23 may not be default on Ubuntu)
          sudo apt-get install -y gcc-13 g++-13

          # Update alternatives to use GCC 13 as default
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
          sudo update-alternatives --config gcc
          sudo update-alternatives --config g++

      # Clean the build directory to remove previous CMake cache
      - name: Clean the build directory
        run: |
          rm -rf build
          mkdir build

      # Set GCC 13 for CMake and specify C++23 standard
      - name: Configure the project with CMake
        run: |
          export CC=/usr/bin/gcc-13
          export CXX=/usr/bin/g++-13
          cmake -S . -B build -DBUILD_TESTS=ON -DCMAKE_CXX_STANDARD=23

      # Build the project
      - name: Build the project
        run: |
          cmake --build build

      # Run the tests
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      # Final message
      - name: Build and test process completed
        run: echo "Build and test process completed successfully!"

