name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Fish shell
      uses: fish-shell/setup-fish-shell@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ fish

    - name: Run build and test script
      run: |
        chmod +x build_and_test.sh
        ./build_and_test.sh

