name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: actions/setup-cmake@v3

      - name: Set up C++ toolchain
        uses: actions/setup-cpp@v1
        with:
          compiler: gcc # or clang
          version: 13 # or 16 for Clang

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: cmake -S . -B build -DBUILD_TESTS=ON

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: cd build && ctest --output-on-failure
